# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Library coordinates, bumped by release-please.
GROUP=com.github.kvs-coder
POM_ARTIFACT_ID=samsunghealthreporter
# x-release-please-start-version
VERSION_NAME=0.0.6
# x-release-please-end
